# DigitalOcean App Platform Configuration
# Deploy this debug container alongside your application to test connectivity

name: debug-container

services:
  - name: debug
    dockerfile_path: Dockerfile
    github:
      repo: bikramkgupta/do-app-debug-container
      branch: main
      deploy_on_push: true
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    routes:
      - path: /

    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Example: Add database connection to test
    # Uncomment and modify as needed:
    #
    # envs:
    #   - key: DATABASE_URL
    #     scope: RUN_TIME
    #     value: ${db.DATABASE_URL}
    #
    # databases:
    #   - name: db
    #     engine: PG
    #     production: false
